PROGRAM = MiniConsole

EXTRA_COMPONENTS = middleware/printf \
		   middleware/osal \
		   middleware/hifc \
		   middleware/serial \
		   middleware/miniconsole

EXTRA_CFLAGS = -funwind-tables

include ../../../../common.mk
